### ISSUE TITLE
How can I get the real userID from mid?

### ISSUE THREAD

**Issue by Thaina** [line/line-login-starter#1]
I am using line login api to get user profile. I got mid of user for account and also displayname. But those cannot be used to add friend to line app

I try to use result of user profile to construct line.me/ti/p/~{id} link and it cannot work with any of them

Are there any API to get userID from mid?

**Comment by GuitarSucks** [comment]
@Thaina 
We will soon release a new version of LINE Login to allow it.
Please wait for notice from Business Center.

**Comment by Thaina** [comment]
@GuitarSucks Thank you very much. Is it likely to be in this year?

**Comment by GuitarSucks** [comment]
I cant commit to it. But I do think it will be this year.
Anyways about  your purpose. We don't support userId with that url scheme.
You can use your LINE@ ID instead, which you can find in [LINE@ Manager](https://admin-official.line.me/) which starts with '@'.

**Comment by Thaina** [comment]
@GuitarSucks What userID that api would give me if I could not used it with that scheme?
Or you mean the current version of API that only give mid?

**Comment by johnjerrico** [comment]
@Thaina check this link https://developers.line.me/web-api/integrating-web-login

**Comment by Thaina** [comment]
@johnjerrico I think you misunderstand my issue

**Comment by johnjerrico** [comment]
sorry @Thaina I think you are right, but  isn't mid is a user id ? how do you plan to add friend ? I don't see any api to add friend; but if you are talking to get the profile of another user .. I believe you need to request their access through the login phase (they need to be invited by your app and they authorize your app to give their profile to you)

**Comment by johnjerrico** [comment]
@Thaina, @GuitarSucks  I don't see any line developer active forum can we create a forum ? so we could exchange some issue or insight .. I myself having trouble intergrating it with owin c#

**Comment by Thaina** [comment]
@johnjerrico Given the actual current userID we can construct a like like `line.me/ti/p/~USERID` which sadly this don't work with mid

**Comment by johnjerrico** [comment]
@Thaina  is it like this link [http://line.me/ti/p/johnjerrico]( http://line.me/ti/p/johnjerrico)  ? we can get the display name through [https://api.line.me/v1/profile](https://api.line.me/v1/profile) .. will this suffice ?

**Comment by Thaina** [comment]
No it's not about displayname. It's about add friend into line app

**Comment by Thaina** [comment]
And displayname is not the same as userID that could be added into line app

User can set userID as ABCDEF that could be found in add friend page. But set displayname as TTTT or anything

Well, you could open your phone and try to click that link. If construct correctly it would open line app for you

**Comment by johnjerrico** [comment]
@Thaina you are right, sorry

**Comment by GuitarSucks** [comment]
Hi All,
We released a new SDK and LINE Login Version 2 yesterday. You can now retrieve the userId.
Thanks and sorry that it was a little delayed

**Comment by Thaina** [comment]
@GuitarSucks Now I can get userID

But then how to use that userID to let user add friend by that id?

**Comment by GuitarSucks** [comment]
@Thaina 
Are you talking about adding @ account as friend of the user?

**Comment by Thaina** [comment]
@GuitarSucks No I mean using `line.me/ti/p/~{id}` or similar with that new userId

**Comment by Thaina** [comment]
@GuitarSucks The point of requesting real userId from the start is. I want people to find and add friend to line app from UI. Instead of telling people to copy their own userId and tell other people to copy and paste it to line. It should be API like `line.me/ti/p/~{id}` so that `{id}` we need to create that link should be able to get from API

**Comment by GuitarSucks** [comment]
Hi @Thaina 
Unfortunately we don't have such API since we don't support user matching type of services.

**Comment by aainc-taminhha** [comment]
Hi @GuitarSucks,

We have the same problem when integrated our application using LINE Login v1 and want to migrate to v2. That we couldn't convert mid of existed users to userId before migrating the application to v2.
Of course, we already checked your migration guideline in FAQ
https://developers.line.me/en/faq/
But there are too many users with the expired access token, so couldn't get their userId for mapping.
Do you have any opinion.

Thank you!

**Comment by chakradharsahoo** [comment]
I want to send message from my website. I want API for send message and getting User id.
I am using API :- https://api.line.me/v2/bot/message/push

For that parameters required :- params_send = {
					  "to": user_id,
					  "messages": message
					}

Where I will get user_id of my contacts and friends. I don't have any API for that getting  user_id of my contacts. Please send me if any one have :- chakradhar.sahoo@navsoft.in or please suggest me 9725381632(India). IF price(Money) required, then i am ready to pay the money.

Please send me the API.

**Comment by chakradharsahoo** [comment]
I ready to pay money for API  for user id of contacts and friends in line and line@.

**Comment by TanPhucLe** [comment]
Hi all,
At now, i have demo which use bot to push message to other account line.
But, I have only **LineId** which Line api has not support to push support.
It only support _userId_, _groupId_, _roomId_ like below link:
https://developers.line.biz/en/reference/messaging-api/#send-push-message

How to any way to get userId from lineId?
Thank you!!!
