### ISSUE TITLE
Can not run this project on heroku 

### ISSUE THREAD

**Issue by a9261** [line/line-login-starter#10]
Is this project up-to-date ? 
I had up load this project to heroku and added keroku parameter by README
but when I try login by my line account. It's always return error 
errorMessage=AUTHENTICATION_FAIL&errorCode=401&error=server_error
How can I test line login or resolve this issue ?

**Comment by KosukeKamiya** [comment]
@a9261 
Yes. It's up-to-date.
Points shown below is common reasons of login fail. Please confirm.
- The LINE account that tries to log-in is not registered to Role of the channel. (If status of your channel is DEVELOPING)
- Callback URL is not registered to the Channel.
