### ISSUE TITLE
How to upgrade Line Login from 1.0 to 2.0

### ISSUE THREAD

**Issue by OraCheung** [line/line-login-starter#13]
Hi,
    As we all know, Line Login 1.0 will return mid for each user, as the same time 2.0 return userId.
    My site used to use mid to identify the user . But when upgrade to 2.0, I can not distinguish between old users. How can I get the real userId from mid? Or how can I get the mid from userId.

**Comment by cosmic-cowboy** [comment]
Hi @OraCheung 

We have an entry to our FAQ related to this issue. Please take a look:
https://developers.line.me/faq#anc6-3

**Comment by OraCheung** [comment]
Hi，
    I know that  method. But v1 API will stop providing API services in January 2018 .Since then, how can I get user mid?

**Comment by KosukeKamiya** [comment]
Hi @OraCheung,
After v1 API will be stopped, there will be no way to get mid.
