### ISSUE TITLE
a999999

### ISSUE THREAD

**Issue by a999999** [line/line-login-starter#14]
"description": "Channel secret",
       "required": true
     },
-    "LINECORP_PLATFORM_CHANNEL_CALLBACKURI": {
-      "description": "Callback URI",
+    "LINECORP_PLATFORM_CHANNEL_CALLBACKURL": {
+      "description": "Callback URL",
       "required": true
     }
   }
src/main/java/com/linecorp/sample/login/infra/line/api/v2/LineAPI.java
@@ -39,7 +39,7 @@
             @Field("grant_type") String grant_type,
             @Field("client_id") String client_id,
             @Field("client_secret") String client_secret,
-            @Field("redirect_uri") String callback_uri,
+            @Field("redirect_uri") String callback_url,
             @Field("code") String code);
 
     @Headers("Content-Type: application/x-www-form-urlencoded")
src/main/java/com/linecorp/sample/login/infra/line/api/v2/LineAPIService.java
@@ -42,15 +42,15 @@
     private String channelId;
     @Value("${linecorp.platform.channel.channelSecret}")
     private String channelSecret;
-    @Value("${linecorp.platform.channel.callbackUri}")
-    private String callbackUri;
+    @Value("${linecorp.platform.channel.callbackUrl}")
+    private String callbackUrl;
 
     public AccessToken accessToken(String code) {
         return getClient(t -> t.accessToken(
                 GRANT_TYPE_AUTHORIZATION_CODE,
                 channelId,
                 channelSecret,
-                callbackUri,
+                callbackUrl,
                 code));
     }
 
@@ -76,16 +76,16 @@ public Profile profile(final AccessToken accessToken) {
 
 
     public String getLineWebLoginUrl(String state) {
-        final String encodedCallbackUri;
+        final String encodedCallbackUrl;
         try {
-            encodedCallbackUri = URLEncoder.encode(callbackUri, "UTF-8");
+            encodedCallbackUrl = URLEncoder.encode(callbackUrl, "UTF-8");
         } catch (UnsupportedEncodingException e) {
             throw new RuntimeException(e);
         }
 
         return "https://access.line.me/dialog/oauth/weblogin?response_type=code"
                 + "&client_id=" + channelId
-                + "&redirect_uri=" + encodedCallbackUri
+                + "&redirect_uri=" + encodedCallbackUrl
                 + "&state=" + state;
     }

**Comment by a999999** [comment]
O

**Comment by cosmic-cowboy** [comment]
@a999999 
Sorry, I don't know what you mean.
So I close this issue.

Issues are used to keep track of bugs and issues and share and discuss them.

Mastering Issues
https://guides.github.com/features/issues/

**Comment by a999999** [comment]
Bye
