### ISSUE TITLE
LINE login for web

### ISSUE THREAD

**Issue by Hsindawg** [line/line-login-starter#15]
Hello,
I saw the document under line login that login authentication is available for web. I would like to know how the login feature works. It seems like I have to ask for an access token and then I retrieve user information through teh token. However, there seems to be a CORS issue if we were to fetch the information. I just want to know what is the correct flow to get the login feature works.
I am using javascript framework to implement this.

Thank you so much.

**Comment by Hsindawg** [comment]
Update: I solved the CORS part, but I still got stuck at retrieving the access token. I followed the document, https://developers.line.me/web-api/integrating-web-login-v2. I wasn't able to fetch the token, it kept giving me error 400 which means one or more of the parameters are wrong which I've followed in the document and put 5 parameters in (grant_type, client_id, client_secret, code, redirect_uri). I just want to know if there is anything in this part I did wrong?

**Comment by TranThanhKhai** [comment]
@Hsindawg You forgot the Request header
Content-Type  application/x-www-form-urlencoded

**Comment by lianbinbin** [comment]
May i ask that how did you solve the CORS part ?

**Comment by TranThanhKhai** [comment]
The browser block the http request from other domain for security reason by default. So, do not send the http request on client side, do it on server side.
